### ISSUE TITLE
Some problem

### ISSUE THREAD

**Issue by Ghtgogo** [ETAOIK/UCAS_Image-Processing_2023Fall#1]
Dear Ge:
       Can we know your answer about image prossessing 2023 paper.
       Can we get your hw7 answer.
       Thank you. Xie xie ge.

**Comment by ETAOIK** [comment]
Dear Ghtgogo:
Thanks for your comments bro! I uploaded HW7 not long ago and hope it can help you. My answer for the final exam will be coming soon as soon as possible, no later than tomorrow morning. Please follow my updates.
Wishing you the best of luck on your exam on Jan 6!

shaunak

**Comment by ETAOIK** [comment]
Dear Ghtgogo:
I uploaded my answers of 2023 final exam of Imaging Processing, hope it could help you and wishing you the best of luck on your exam again!

shaunak
