### ISSUE TITLE
1

### ISSUE THREAD

**Issue by jarvisyyk** [ETAOIK/UCAS_Image-Processing_2023Fall#2]
Excellent work for your wonderful pack for Image Processing, which bothers me a lot.
But after finishing the 2023 paper you uploaded, I feel no more nervous and anxious(our 2024 exam is imminent, in December 28)
But for the purpose of better future for your work, there are some problems in it.
In 2023 paper, the answer to the Blanks filling 10th is wrong I insist,which should be 1/4(2 2 -2 -2 0.....0)
and the same mistake exists in your homework 7, the Harr matrix should add a 1/sqrt(16) ahead of the whole matrix.
Thanks again for your wonderful work. 
With the 2025 is imminent, may the best luck be with U.

**Comment by ETAOIK** [comment]
Dear jarvisyyk,
    I apologize for the late reply, and I hope you have achieved a satisfactory result in the final exam on December 28.
    Really grateful for your great kindness, pointing out the simple errors in my answers of HW7 and 23 final exam, which allowed me to revisit and correct my misunderstandings of Haar transformation. I sincerely appreciate your helpful reminder!
    So glad to see your helpful message before 2024 comes to its end hhh, I also wish you a happy and fulfilling in the coming new year, and with all the best in your scientific research! ☺️

yours
Shaunak
